### ISSUE TITLE
about the API_KEY in README.MD

### ISSUE THREAD

**Issue by icools** [dkexception/ChatGPT-Android-App#1]
The suggestion is to add a note in Readme.md about the format of the API key, specifically that it should be in the format openAIBackendSecretKey = "Bearer ${API_KEY}" instead of openAIBackendSecretKey = "${API_KEY}", as some people may assume the latter. Thank you.

**Comment by dkexception** [comment]
Updated the README.md file as suggested - https://github.com/dkexception/ChatGPT-Android-App/commit/c752ef5e2293deb6aac46da66e82d8c499ab020d

Thanks for noticing this!
